# Generated by Django 4.1.7 on 2023-02-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('dateofjoining', models.DateField(auto_now_add=True, verbose_name='Date of Joining')),
                ('department', models.CharField(max_length=100, verbose_name='Department')),
                ('salary', models.CharField(max_length=20)),
            ],
        ),
    ]
