# Generated by Django 4.1.7 on 2023-02-16 08:41

from django.db import migrations

def create_data(apps, schema_editor):
    Employee = apps.get_model('employees', 'Employee')
    Employee(name="Shiffana Nazeema", email="shiffananazeema@gmail.com", phone="9384745010", department="Python Full Stack", salary="$6000").save()

class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
